### PR TITLE
Vt Precincts

### PR DESCRIPTION
**Pull request by wboykinm**
per #48 

@nvkelso After chopping away at this myself using existing boundaries, [VCGI](http://vcgi.vermont.gov/) took pity on me and created an accurate precinct layer in consultation with the VT SoS's office. These supersede legislative house and senate districts as the smallest units at which the SoS reports election results. 

rutland

### CODE REVIEW

**Comment by nvkelso** [comment]
Awesome! 

Are these publicly available anywhere? I generally try to link back there in a README.md file in the state dir, or note they were sent via private channel on such and such date with contact info.

**Comment by nvkelso** [comment]
Shapefile checks out. I'll need to update the Makefile part to build using the new source, though:

https://github.com/nvkelso/election-geodata/blob/master/Makefile#L762-L767

I'll push new commits into this branch.

**Comment by wboykinm** [comment]
@nvkelso Def. I received the early release from Leslie Pelch (Leslie.Pelch@vermont.gov) of VCGI on Jul 18th, after consulting on how they would coordinate results matching with the VT Sec. of State. The file will be available on http://geodata.vermont.gov/ within a few weeks, at which point I'll add the permalink.

**Comment by nvkelso** [comment]
Some notes:

- OGR doesn't like spaces or - in filenames so replaced spaces with _ for ZIP file in https://github.com/nvkelso/election-geodata/pull/113/commits/6fb7c5cf7523abeaa323ad348f0fb7b2a0e6594f.
- Makefile updated to use new Vermont source in https://github.com/nvkelso/election-geodata/pull/113/commits/2b027ffd8565662d23555a344937d51da63317f6
- Reverted removing the shell script, it's still useful history. https://github.com/nvkelso/election-geodata/pull/113/commits/3e809600ba71b18343536df403d16c06e4b989bb
- Added basic Vermont README file in https://github.com/nvkelso/election-geodata/pull/113/commits/140e7562af37ca497b127c3ccb39004a169b3fe8

I updated the Makefile with 2016 as the currency date as this is fresh data circa 2017 that I assume is accurate to 2016 election. Please correct that if not accurate!

Resulting status map:

render

CircleCI is failing because it's hitting a 30 minute time out (not having to do with this PR). Looking into that separately.

**Comment by nvkelso** [comment]
@wboykinm Please confirm 2016 as the "year" of the new Vermont data and then this PR will be ready to merge.

**Comment by nvkelso** [comment]
(We can modify the date in another PR if it's not actually 2016.)

**Comment by wboykinm** [comment]
@nvkelso Yeah, the map was finalized by the legislature in 2012, but obv 2016 is still the same boundaries.

**Pull request merged**
