### PR TITLE
Switch from Circle to Docker

### PR DESCRIPTION
**Pull request by migurski**
We’ve outgrown Circle CI and need another way to run data and tests. For the time being, it might be acceptable to run this manually under Docker as a jury-rigged replacement.

- [x] Build a Dockerfile with complete dependencies.
- [x] Add Test commands to Dockerfile.
- [x] Add deployment commands to Dockerfile.
- [x] Integrate with Github Statuses.
- [x] Verify that @nvkelso can run this from documentation.

### CODE REVIEW

**Comment by happyjack27** [comment]
I've never really gotten this idea of CI.  Do people not build and test it
on their local PC before commiting?  And then before release, isn't there a
more comprehensive testing?

Really, if your code doesn't even frickin compile, why the hell would you
commit?

**Comment by migurski** [comment]
@happyjack27, in this case we’re using CI to prepare data. It’s a sanity check and a build step all in one.

**Comment by happyjack27** [comment]
And this step isn't done on the local machine before commiting?

**Comment by migurski** [comment]
It will be now, because it takes too long for Circle CI’s 30min limit. Ordinarily we wouldn't want to do it locally: it’s annoying to need all the low-level packages installed if you’re contributing data changes, and it’s nice to have someone else’s CPU doing the work for free. Docker helps ease the pain of the first thing.

**Comment by happyjack27** [comment]
K, thanks.

That helps me understand the role / use case.

**Comment by migurski** [comment]
Nathaniel, if you’re interested in trying this out, get in touch. I’ll provide you with AWS keys and secrets for the `env.ini` file.

0. Get Docker and a local checkout of this branch.
1. Build the Docker image from `docker/Dockerfile`:
    
        docker build -t nvkelso/elections-geodata docker
    
2. Populate your local `env.ini` file with a Github token and AWS keys/secrets.
3. Run tests and publish data, which can take an hour or so:
    
        docker run --env-file env.ini --rm -v `pwd`:/vol -w /vol nvkelso/elections-geodata

**Comment by nvkelso** [comment]
Everything seems to be working...

But is the S3 location right? See below – seems to be putting into a commit path instead of something the README.md can constantly link to?

```
+ export GIT_SHA1=e0cc26103f9f5b675611d1164feb1d05295cade0
+ git rev-parse --abbrev-ref HEAD
+ export GIT_BRANCH=migurski/add-docker-support
+ aws --region us-east-1 s3 cp --acl public-read out/render.png s3://nvkelso-election-geodata/commits/e0cc26103f9f5b675611d1164feb1d05295cade0/render.png
upload: out/render.png to s3://nvkelso-election-geodata/commits/e0cc26103f9f5b675611d1164feb1d05295cade0/render.png
+ [ migurski/add-docker-support = migurski/add-docker-support ]
+ aws --region us-east-1 s3 cp --acl public-read --cache-control max-age=60 public out/render.png s3://nvkelso-election-geodata/branches/migurski/add-docker-support/render.png
upload: out/render.png to s3://nvkelso-election-geodata/branches/migurski/add-docker-support/render.png
```

**Comment by nvkelso** [comment]
One final question:

```
ogr2ogr out/nation.shp out/nation.gpkg
```

I thought we only made gpkg files, are you adding support for SHP distribution in ZIP, too with this PR?

**Comment by migurski** [comment]
It does both commit path and branch path:

- Every commit on every branch gets a render: https://s3.amazonaws.com/nvkelso-election-geodata/commits/e0cc26103f9f5b675611d1164feb1d05295cade0/render.png
- Commits on the deployment branch get renders and packages which appear on the front page README: https://s3.amazonaws.com/nvkelso-election-geodata/branches/master/render.png
- Right now those are going to the PR branch so we can check that they work: https://s3.amazonaws.com/nvkelso-election-geodata/branches/migurski/add-docker-support/render.png

I added the shapefiles back in March: https://github.com/nvkelso/election-geodata/commit/ff28fead5646558b1fc0bf88c0361850abcf294f#diff-29944324a3cbf9f4bd0162dfe3975d88

**Comment by nvkelso** [comment]
Cool, all this works for me (verified locally with Docker).

**Comment by migurski** [comment]
Great, going to merge and then disable Circle for this project!

**Comment by migurski** [comment]
Hm, as the owner of the repo you may need to do the Circle disabling. I’m running the master branch right now to update the README render and published data.

**Comment by nvkelso** [comment]
I've manually stopped the CircleCI builds via their interface.

**Comment by migurski** [comment]
FYI, I added a Make rule for the two Docker steps: https://github.com/nvkelso/election-geodata/blob/b04e930a74dee00a317b3f0a1c4f330f7120ca95/Makefile#L6-L10

**Pull request merged**
