### PR TITLE
Perform IA and NM precinct county assignments

### LINKED ISSUE #161: Iowa precincts have no county assignment
Available Iowa precinct geodata does not include county assignments. Generally, Iowa precincts are entirely contained by one county, so precincts should have county assignments.

### PR DESCRIPTION
**Pull request by sigpwned**
Closes #161.

Note that this PR updates the Dockerfile for the build image. The change is necessary because the existing build image uses an older version of GDAL that doesn't support spatial functions in GPKG files and spatial functions are required to see which county each precinct belongs in. There is not an obvious alternative to GPKG format that would support spatial functions at the current GDAL level. Fortunately, the changes to the Dockerfile are fairly simple.

### CODE REVIEW

**Comment by sigpwned** [comment]
> This does involve some Docker file changes that put us on newer Ubuntu and away from @migurski's PPAs with pegged versions so let's get a review from him before merging.

Absolutely.

When I saw that we had to move away from @migurski's PPA, I tried to find another repo that seemed reasonable as a substitute, and landed on the official Ubuntu GIS package repo. That feels safe, but I totally understand that it still may not be the right approach for stability's sake.

Again, the missing feature in the existing docker is the ability to use [spatialite functions](http://www.gaia-gis.it/gaia-sins/spatialite-sql-4.2.0.html) in `ogr2ogr`. Per [the GDAL documentation](https://www.gdal.org/drv_geopackage.html), the magical versions to hit are:

* GDAL >= 2.0
* spatialite >= 4.2

The "new" Dockerfile gets us `libspatialite7`, which hits the above spatialite target. The "old" Dockerfile gets us `libspatialite5`, which is version 4.1.1 < 4.2.

**Comment by nvkelso** [comment]
There was a while when GDAL was in the later 1.x series that updates were sporadic but in the 2.x in the last 2 years it's picked up quite a bit in a good way.

@migurski do you want to update your PPA with newer GDAL and Spatialite support as described here or should we move to the standard distribution?

**Comment by nvkelso** [comment]
That's life ;)

**Comment by nvkelso** [comment]
@migurski Can you take a look, please?

**Comment by migurski** [comment]
Great changes! 

I’ve had a lot of problems with GDAL versions from the Ubuntu GIS PPA in the past, so I think it’s better and more future-proof to use pinned versions from a purpose-specific PPA like the `ppa:migurski/electionsgeodata` one here. It doesn’t have to be mine, but it should be one that won't experience unexpected updates. I would be happy to add everyone here as a maintainer of my PPA, or to help switch to an @nvkelso -owned PPA.

A brief summary of Ubuntu GIS problems: GDAL and related packages have older versions included in base Ubuntu. If you simply `apt-get install gdal-bin` you’ll get those older versions instead of the new ones in Ubuntu GIS. A solution is to specify exact pinned versions, but those become unavailable over time. Copying packages to a project-specific PPA ensures that they remain available into the future.

**Comment by migurski** [comment]
I see no drawback to using 16.04. It’ll be supported long-term, we should take advantage of that.

> How does one copy packages to a project-specific PPA? The ubuntu GIS PPA is currently working -- or, at least, was as of a couple of weeks ago -- so can we just perform some kind of copy/paste from there?

That’s pretty much it! There’s a [“copy packages” link on Launchpad that looks like this](https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable/+copy-packages):

screen shot 2018-10-01 at 2 28 02 pm

You can simply copy the binaries over, and then you have a point-in-time pinned version of a particular package in personal package archive. I don't have a strong preference on the two options; a third might be to create a team organization for this project and add each of us. At the moment I’m unable to find a setting that allows others to join or edit a user-PPA, but [I’ve created teams like OpenAddresses with multiple users](https://launchpad.net/~openaddresses/+members#active).

**Comment by sigpwned** [comment]
Thank you for the very clear instructions, @migurski! @nvkelso, how would you like to proceed? Would you like to set up the PPA with the relevant packages? Or I can do it if that's easier for you; it should be possible for me to create a PPA and assign it back to you.

In any case, I would propose that we handle this in a separate issue. It should build with the current `ubuntugis` settings, and then I'll open up a ticket to fix the docker image and quickly fix it with the new PPA. That will keep this PR (and several others that depends on it) clean and easy.

**Comment by migurski** [comment]
Agreed that we can switch to Ubuntu GIS for the time being, with a plan to switch PPA’s to one with a pinned version. 

Nathaniel, I’ve been having a hard time finding a way to add collaborators to my personal one, so I have created a new [Election Geodata PPA](https://launchpad.net/~election-geodata/+archive/ubuntu/ppa/). If you create a Launchpad account, I can add you as an admin to that team.

**Comment by sigpwned** [comment]
@migurski Great! I'll open the new "change to PPA" issue as soon as this one is integrated.

@nvkelso Are you comfortable with the Dockerfile change, given @migurski's input and the plan to change to a PPA soonest in a separate issue?

**Comment by nvkelso** [comment]
Yep!

**Comment by nvkelso** [comment]
@migurski I'm `nvkelso` over there.

**Comment by nvkelso** [comment]
Builds locally for me, let's merge these!

**Pull request merged**
