### PR TITLE
Added Wisconsin ward shapes

### PR DESCRIPTION
**Pull request by migurski**
Part of #2 — do we close these issues?

This data uses polling place centroids to generate ward shapes via Voronoi tesselation. Many polling places serve multiple wards. I wanted one row per ward, so many of the shapes overlap.

Copied data from https://github.com/migurski/Redistricting/blob/d90b4be40744/55%20-%20Wisconsin/polling_place_locations_2016_nov_general_xlsx_81288_polygons.geojson.gz

wi

### CODE REVIEW

**Comment by nvkelso** [comment]
I see the overlap in the GH GeoJSON preview:

image

**Comment by nvkelso** [comment]
Regarding closing #2 or not... one thing Geraldine and I have done for Cartography work before is bucket the work into `functional` and `polished` subtasks. This feels `functional`, but not `polished`. I suspect we can clean up a bunch of this with the township data, and maybe 10 counties worth of more detailed ward shapes, at which point I'd feel more comfortable closing #2. I'll do a little management over there.

Can you also add the src file that has the poling places and their lat/lngs to this PR (so the derived Voronoi can be regenerated), and then I think it's ready to merge.

**Comment by migurski** [comment]
Points file added! It’ll be interesting to try to patch in parts of the state where data is better, see if those can coexist with these shapes. Maybe these can be broken down by county and intersected with those polygons.

**Comment by nvkelso** [comment]
Probably the state shape minus townships coterminous with precinct to clip the tessellated precinct points, then added together with those coterminous townships.

**Comment by migurski** [comment]
Yeah exactly.

**Pull request merged**
