### PR TITLE
add Wisconsin state name in national output

### PR DESCRIPTION
**Pull request by nvkelso**
Fixes https://github.com/nvkelso/election-geodata/issues/82 (and really a simple test of @migurski's latest CI work.)

### CODE REVIEW

**Comment by nvkelso** [comment]
Verified in output. Not sure where @migurski's CI work is ... in flight?

**Comment by migurski** [comment]
What are you looking for? The GPKG and Shapefiles are uploaded as part of a master branch deploy, so only the rendered PNG map would appear in a PR. Is that what you’re asking about?

**Comment by nvkelso** [comment]
Yes, image in PR never shows up.

**Comment by migurski** [comment]
Ah, it shows up here:

screen shot 2017-03-13 at 10 40 04 pm

I'm not posting a comment or anything, just a commit status.

**Comment by migurski** [comment]
Ah wait, you might mean the image on the front page  README. Github has some kind of caching HTTPS proxy there, and I've tried to set the cache timeout in S3 to keep it fresh. It doesn’t quite seem to work, though. More info here: https://help.github.com/articles/about-anonymized-image-urls/

**Pull request merged**
