### PR TITLE
Use complete NH precinct file

### PR DESCRIPTION
**Pull request by wboykinm**
Hot off the presses from the NH Office of Strategic Initiatives, we have a shapefile of all post-2012 NH voting precincts, down to the wards detailed [in the issue thread](https://github.com/nvkelso/election-geodata/issues/42#issuecomment-286913534)

These will shortly be available on the [NH GRANIT portal](http://www.granit.unh.edu/) as well.

### CODE REVIEW

**Comment by migurski** [comment]
Ooh

**Comment by wboykinm** [comment]
@nvkelso Note that the 'precinct' transform previously used here . . .

`CONCAT('33', CAST(FIPS AS character(3))) AS precinct`

. . . isn't strictly accurate now. Every ward in a given city shares a FIPS code, so a ward number will need to be scraped off and appended, ideally in keeping with the way the SoS delivers results. Maybe something like this:

`(CASE WHEN WARD LIKE '%Ward%' THEN CONCAT('33', CAST(FIPS AS character(3)),'-', RIGHT(WARD,1)) ELSE CONCAT('33', CAST(FIPS AS character(3))) END) AS precinct`

. . . though I'm not sure if SQLite syntax will support that.

**Comment by wboykinm** [comment]
screenshot 2017-10-24 17 06 04

**Comment by wboykinm** [comment]
@nvkelso Y'all are pretty busy I'm sure, but any chance of a look at this one?

**Pull request merged**
