### PR TITLE
Replaced colors with a mix of Solarized gray and Brewer greens

### PR DESCRIPTION
**Pull request by migurski**

### CODE REVIEW

**Comment by nvkelso** [comment]
Preview image?

**Comment by migurski** [comment]
It’s part of the status checks:

https://s3.amazonaws.com/nvkelso-election-geodata/commits/0bc874b286ccfec9b7d3636777823ee2c47b0c9c/render.png

**Comment by nvkelso** [comment]
I dig the new colors :)

Can it comment that image into the issue after the run?

**Comment by migurski** [comment]
Sure; that's a bit of extra work but yeah, I can probably make it do that.

**Pull request merged**
