### PR TITLE
NH macro (town) boundaries

### PR DESCRIPTION
**Pull request by wboykinm**
Per #42, these are NH's "precincts" (they call them "voting districts") for _most_ of the land area of the state. Cities are divided into wards, which may need to be added piecemeal. Towns + wards = complete NH precincts.

### CODE REVIEW

**Comment by nvkelso** [comment]
LGTM, thank you!

I did a quick visual analysis in QGIS comparing the older US Census 2010 VTD shapes with this 2016 geographies and where there are a few tiny differences along some boundaries and with the Atlantic Ocean clip, they are otherwise 100% the same.

screen shot 2017-03-14 at 20 28 23

The areas that are colored have the wards, circa 2010 and are `FUNCSTAT10='S'`. These match the following 2016 areas `FIPS IN (1035,1040,5045,7020,9110,11085,11110,13040,13060,15040,15145,17010,17050,17060,19015)`. Ill update the Makefile.

**Comment by nvkelso** [comment]
Updated the Makefile in https://github.com/nvkelso/election-geodata/pull/95/commits/482e670abf5bdcef55f97b8ef68e00ab3bb46438, resulting in a mostly blue New Hampshire for the **towns** (and presumably most the older 2010 **wards** data is still valid in 2016, but...):

render

**Comment by wboykinm** [comment]
@nvkelso Unfortunately I checked ward boundaries in three cities where current PDF maps are available (Lebanon, Manchester, Dover), and the 2010 lines were significantly altered in the 2012 redistricting.

**Comment by nvkelso** [comment]
Fun times :)

Can you share links to those PDFs?

**Comment by wboykinm** [comment]
@nvkelso Definitely - will add to #42

**Pull request merged**
