### PR TITLE
Added probably-incorrect Idaho 2001 precincts

### PR DESCRIPTION
**Pull request by migurski**
Part of issue #10.

- [ ] Figure out what’s up with the projection [described in this comment](https://github.com/nvkelso/election-geodata/issues/10#issuecomment-285409670).

It reports as tranverse mercator, but reprojecting to 4326 puts it near the equator:

id

### CODE REVIEW

**Comment by migurski** [comment]
Also added Nez Perce 2006 precincts.

nez-perce

**Comment by nvkelso** [comment]
@migurski Probably needs false northing specified.

**Comment by migurski** [comment]
Would it be acceptable to guess at the value and drop it in, or is there a more scientific way to do this?

**Comment by nvkelso** [comment]
I'll have a look tonight....

**Pull request merged**
