### PR TITLE
WIP: 193 build process uses ubuntugis ppa for gdal support

### LINKED ISSUE #193: Build process uses ubuntugis PPA for GDAL support
PR #162 changed the Dockerfile to use the ubuntugis PPA for GDAL support. This is likely to cause problems in the future as that PPA changes its package versions. We should change to [this bespoke PPA](https://launchpad.net/~election-geodata/+archive/ubuntu/ppa/) for this project, per conversation with @migurski @nvkelso [here](https://github.com/nvkelso/election-geodata/pull/162#issuecomment-426070717).

### PR DESCRIPTION
**Pull request by sigpwned**
Updates Dockerfile to use bespoke PPA. Closes #193.

### CODE REVIEW

**Comment by nvkelso** [comment]
@sigpwned Can you resolve the conflicting files and then I'll have a look?

**Comment by sigpwned** [comment]
@nvkelso will do!

**Comment by nvkelso** [comment]
@migurski Can you take a look at this PR, please? I resolved the merge conflicts but when running:

> $ docker run -it -v `pwd`:/vol -w /vol --env-file docker/env.ini eg

I get the following error:

```
: invalid option
```

**Comment by nvkelso** [comment]
Related, but can @sigpwned can you update to GDAL 2.2.x or newer as the current PPA is on 2.1 and uses a different structure to address GeoJSON files by name instead of universal alias and causes problems for me when running the Makefile in Docker versus just locally.

- https://launchpad.net/~sigpwned/+archive/ubuntu/election-geodata
- https://www.gdal.org/drv_geojson.html

**Pull request merged**
