### PR TITLE
Render Hawaii and Alaska

### PR DESCRIPTION
**Pull request by migurski**
I’m cheating by sticking with EPSG:2163, so they look a little tilty:

👍?  👎?

### CODE REVIEW

**Comment by nvkelso** [comment]
Can you rebalance AK and Hawaii to their own projections, please? Otherwise good :)

**Comment by migurski** [comment]
[](https://s3.amazonaws.com/nvkelso-election-geodata/commits/2bdac12e6cacbba1098bc1fa10c03973eb0bef49/render.png)

**Comment by nvkelso** [comment]
Nice! Can Puerto Rico be added, too?

**Comment by migurski** [comment]
Yup!

**Pull request merged**
