### PR TITLE
Expanded Kansas rules to include new statewide data

### PR DESCRIPTION
**Pull request by migurski**
Follow-on to https://github.com/nvkelso/election-geodata/pull/60. Starts to introduce some complexity in the Makefile to pick best-available data per county. 

- [ ] Wait to use the newer data after #68 is merged.

render

### CODE REVIEW

**Comment by karpet** [comment]
love this.

I just opened #68 which includes 2012 data -- maybe wait on this to use the newer data after #68 is merged?

**Comment by migurski** [comment]
Good idea, I’ll add a note to the description.

**Comment by nvkelso** [comment]
More data the merrier :)

**Comment by nvkelso** [comment]
#68 has been merged

**Comment by nvkelso** [comment]
Verified this still looks good, merging.

**Pull request merged**
