### PR TITLE
Add shapefile and geopackage upload

### LINKED ISSUE #80: Write the out nation gpkg to S3
And since Shapefile is more common, that too as a zip.

### PR DESCRIPTION
**Pull request by migurski**
Closes #80.

### CODE REVIEW

**Comment by migurski** [comment]
Examples from just this branch:

- https://s3.amazonaws.com/nvkelso-election-geodata/branches/migurski/configure-circle-render/render.png
- https://s3.amazonaws.com/nvkelso-election-geodata/branches/migurski/configure-circle-render/nation.gpkg
- https://s3.amazonaws.com/nvkelso-election-geodata/branches/migurski/configure-circle-render/nation-shp.zip

**Comment by nvkelso** [comment]
Hmm, I only see Kentucky on the map using the SHP in QGIS, but I see attribute table rows for all states. Same problem in the GeoPackage thingy. @migurski Do you see the same (missing) data?

**Comment by nvkelso** [comment]
(But other than that the PR looks good!)

**Comment by migurski** [comment]
I did see some projection warnings float by in the Circle log — do you think the data is somehow wrong?

**Pull request merged**
