### PR TITLE
Add 2016 shapefiles for populous KS counties

### PR DESCRIPTION
**Pull request by karpet**
Addresses #124 

Converting the existing Douglas co shapefile to CRS84 since that seems to play more nicely with the GH preview feature.

### CODE REVIEW

**Comment by nvkelso** [comment]
_waits for the GH preview via Docker workflow to post here..._

**Comment by nvkelso** [comment]
Oh, Kansas uses an [non-standard setup](1ff5d871c77ef1af406c4ab2683f924fR10) compared to the other states by building with a shell script. That's fine, just different, and this PR doesn't change that – instead building on it.

But it looks like line 10 needs to be updated to exclude the newly added counties:

`ogr2ogr -sql "SELECT '2012' AS year, 'Kansas' AS state, SUBSTR(VTD_2012, 3, 3) AS county, VTD_2012 AS precinct, 'polygon' AS accuracy FROM OGRGeoJSON WHERE SUBSTR(VTD_2012, 3, 3) NOT IN ('045', '091', '173', '209')" \`

Chaning it to a NOT IN list as above. Otherwise the older 2012 data will be there in addition to the 2016 data for those new 3.

**Comment by karpet** [comment]
You're right - I neglected to fix that sql in my 2nd PR attempt. Fixed in 36b0f43

**Comment by nvkelso** [comment]
I'm fine with merging early and often.

**Pull request merged**
