### PR TITLE
Added more Github status updates

### PR DESCRIPTION
**Pull request by migurski**
- [x] Add `pending` and `failure` status updates to act more like a real CI.
- [x] Figure out if it’s possible to add comments with rendered images. Challenge: we don’t actually know the PR# involved, and would have to guess.
- [x] Post a comment with rendered image to PR thread.

@nvkelso: in order for comments to work, your Github token will need to have both `repo:status` and `public_repo` scopes turned on.

### CODE REVIEW

**Comment by migurski** [comment]
Testing 1

**Comment by migurski** [comment]
Testing in code

**Comment by migurski** [comment]
Testing in code

**Comment by migurski** [comment]
Testing in code

**Comment by nvkelso** [comment]
✅ For those following along it's as simple as changing a checkbox on the token page and saving (no need to generate a new token).

**Comment by migurski** [comment]
Ah yeah, I’ve been deleting them. Sorry.

**Comment by migurski** [comment]
(With luck, we’ll see a real one shortly and then we can close out this PR)

**Comment by migurski** [comment]
Preview for commit e1cebc6be8072b201fa9e6ec42496c9547f0c536:

**Comment by migurski** [comment]
All right, calling this a wrap.

**Comment by nvkelso** [comment]
🎉

**Pull request merged**
